### ISSUE TITLE
[WinError 5] Denial of access~~~~/pack-fccb703fa47a9df8e4bce0758f4226644fc702a0.idx'

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#215] opened 2023-10-12 01:04 UTC
It shows in startup CMD: But [ComfyUI-Impact-Pack) still can running without problem
[WinError 5] Denial of access。: 'F:\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack\\.git\\objects\\pack\\pack-fccb703fa47a9df8e4bce0758f4226644fc702a0.idx'

how about this error, can I delete this file？

**Comment by ltdrdata** [comment] 2023-10-12 01:10
It seems that the file is being used somewhere, which could be the cause of this issue.
If the file becomes corrupted, it may lead to problems in future updates, among other issues. 

To address potential problems, I recommend closing ComfyUI, uninstalling the Impact Pack. If it still doesn't work, consider rebooting your computer, uninstalling the Impact Pack, and then reinstalling it.

**Closed as completed by ltdrdata** 2023-10-12 01:10 UTC
