### ISSUE TITLE
Wildcard files not read from subfolders

### ISSUE THREAD

**Issue by tusharbhutt** [ltdrdata/ComfyUI-Impact-Pack#220] opened 2023-10-12 17:27 UTC
It looks like Impact Pack's Wildcard processor will not load files that are in subfolders.  I've never used it before so not sure if it was build in functionality or if something has gone wrong, but the [ComfyUI DynamicPrompts](https://github.com/adieyal/comfyui-dynamicprompts) module is having the same issues and it worked last week as well, so maybe it has something to do with the ComyUI update from last week.  The screenshot below shows the folder structure, what the file content is of "figurines.txt" and how it calls the other files, the ImpactNode result, and the error message.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/26264462/b3c71c60-3541-455d-999e-33e366eddbdc)

Here is the error message for better readability:

```[ERROR] An error occurred while retrieving information for the 'WildcardEncode //Inspire' node.
Traceback (most recent call last):
  File "C:\Applications\StableDiffusion\ComfyUI\server.py", line 417, in get_object_info
    out[x] = node_info(x)
  File "C:\Applications\StableDiffusion\ComfyUI\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "C:\Applications\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\prompt_support.py", line 318, in INPUT_TYPES
    wildcards = nodes.NODE_CLASS_MAPPINGS['ImpactWildcardEncode'].get_wildcard_list()
AttributeError: type object 'ImpactWildcardEncode' has no attribute 'get_wildcard_list'
```

I looked at the various Pytho files in the [DynamicPrompts Library](https://github.com/adieyal/dynamicprompts) and it seems the key is to load a tree of files, but that is failing now.

**Comment by ltdrdata** [comment] 2023-10-12 23:02
Update your Impact Pack to latest version.

**Comment by tusharbhutt** [comment] 2023-10-13 04:59
It's already up to date.

**Comment by ltdrdata** [comment] 2023-10-13 05:17
> It's already up to date.

How is the `Impact Pack version` displayed when starting ComfyUI?

This is correct version.
```
### Loading: ComfyUI-Impact-Pack (V4.18.6)
```

**Comment by tusharbhutt** [comment] 2023-10-13 06:43
Here you go...

```
Total VRAM 12287 MB, total RAM 16335 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.18.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Inspire-Pack (V0.28.1)
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: 1563 [fee3b0c0] | Released on '2023-10-12'
```

**Comment by ltdrdata** [comment] 2023-10-13 08:08
Please send me your workflow. 

Additionally, from your screenshots and mentions, it appears that you are using ImpactWildcardProcessor, but the error message indicates the use of Inspire's `WildcardEncode`. Please clarify the situation.

**Comment by tusharbhutt** [comment] 2023-10-13 19:08
Here is the workflow JSON, the image with the embedded JSON and a ZIP file with the wildcards that preserves the path.  If I use the pattern \_\_\*\\wildcard__, the file _does_ load properly, but any wildcard files referenced within are still only loaded as the name and not the content.  My expectation was that those files would have their content loaded recursively, like DynamicPrompts used to do until the ComfyUI update made it inoperable. 

![ImpactWildCard_0001](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/26264462/bcc52f16-be91-4c22-ab99-74737b5eacad)

[ImpactWildcardTest.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12897764/ImpactWildcardTest.json)
[wildcards.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12897765/wildcards.zip)

[ImpactWildCard_0001.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12897762/ImpactWildCard_0001.json)

**Comment by ltdrdata** [comment] 2023-10-14 01:56
> Here is the workflow JSON, the image with the embedded JSON and a ZIP file with the wildcards that preserves the path. If I use the pattern __*\wildcard__, the file _does_ load properly, but any wildcard files referenced within are still only loaded as the name and not the content. My expectation was that those files would have their content loaded recursively, like DynamicPrompts used to do until the ComfyUI update made it inoperable.

That's a different issue from the error logs above. In any case, the reason the nested wildcard isn't resolving is that it's being populated as `__halloweenfigure__`, but halloweenfigure.txt is not in the wildcard root, it's in the figurine subfolder. In this case, it should have originally been `__figurine/halloweenfigure__` or `__*/halloweenfigure__`.

I just updated it so that when there's no subfolder specified like `__halloweenfigure__` and no match is found, it will automatically insert `__*/halloweenfigure__` for a retry. In that scenario, this issue should no longer occur.

**Closed as completed by ltdrdata** 2023-10-14 01:56 UTC

**Comment by tusharbhutt** [comment] 2023-10-17 03:09
Thanks for that!  However there are still scenarios where wildcards in subfolders do not parse correctly if they call wildcards in other subfolders, especially with multiple levels of subfolders.


In the folder structure below, the folder **ThePasssage,** is within the **wildcards** folder and has a folder called **Astronauts**.  
Within this folders is a  wildcard called \_\_astronauts\_\_ , which can randomly call \_\_female astronaut\_\_ or \_\_male astronaut\_\_, each of which references \_\_ethnicity\_\_, which resides in **wildcards\\royalty** 


![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/26264462/266ff8ef-4217-491f-b466-71e5c14a0ffc)


 
If \_\_female astronaut\_\_  was selected and references \_\_ethnicity\_\_ , that file will not be called, nor will the prompt work.  
Instead, a random selection from another file is grabbed. Sometimes it's a complete prompt from the proper files (very, very rare), more often it is a single result from some random file within the random wildcard folder.  Sometimes it's half the prompt, and some of the wildcards remain in the prompt without being parsed.  See below for some examples

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/26264462/a291c19a-27b1-460d-acd0-22f6c0686bc6)


![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/26264462/ab816f10-2101-4d0c-a352-701eb4bcd39a)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/26264462/af0e2456-6309-4b9c-9c80-3ee0f505eb43)

**Comment by ltdrdata** [comment] 2023-10-17 04:31
> Thanks for that! However there are still scenarios where wildcards in subfolders do not parse correctly if they call wildcards in other subfolders, especially with multiple levels of subfolders.
> 
> In the folder structure below, the folder **ThePasssage,** is within the **wildcards** folder and has a folder called **Astronauts**. Within this folders is a wildcard called __astronauts__ , which can randomly call __female astronaut__ or __male astronaut__, each of which references __ethnicity__, which resides in **wildcards\royalty**
> 
> ![image](https://user-images.githubusercontent.com/26264462/275699784-266ff8ef-4217-491f-b466-71e5c14a0ffc.png)
> 
> If __female astronaut__ was selected and references __ethnicity__ , that file will not be called, nor will the prompt work. Instead, a random selection from another file is grabbed. Sometimes it's a complete prompt from the proper files (very, very rare), more often it is a single result from some random file within the random wildcard folder. Sometimes it's half the prompt, and some of the wildcards remain in the prompt without being parsed. See below for some examples
> 
> ![image](https://user-images.githubusercontent.com/26264462/275699148-a291c19a-27b1-460d-acd0-22f6c0686bc6.png)
> 
> ![image](https://user-images.githubusercontent.com/26264462/275699206-ab816f10-2101-4d0c-a352-701eb4bcd39a.png)
> 
> ![image](https://user-images.githubusercontent.com/26264462/275699275-af0e2456-6309-4b9c-9c80-3ee0f505eb43.png)

That is not a subfolder problem. It's because wildcard contains `space`. Impact wildcard doesn't allow space for wildcard name including subfolder.

`__astronaut_ship__` is ok. But, `__astronaut ship__` isn't. If wildcard allows that space character then prompt will be disaster.

**Comment by tusharbhutt** [comment] 2023-10-18 15:55
Thanks again for the insight, I wonder how DP gets away with spaces in filenames, but it doesn't matter 'cause the node doesn't work :)

I see your point on how spaces in filenames can be risky. I also see your code is way different from the DP library that was put out so I do appreciate all the hard work you've put into making this available to the community.

**Comment by ltdrdata** [comment] 2023-10-18 16:16
> Thanks again for the insight, I wonder how DP gets away with spaces in filenames, but it doesn't matter 'cause the node doesn't work :)
> 
> I see your point on how spaces in filenames can be risky. I also see your code is way different from the DP library that was put out so I do appreciate all the hard work you've put into making this available to the community.

Supporting spaces in file names itself is possible, but the issue is that it can lead to ambiguous and potentially messy behavior.

For instance, if you have a prompt like `__aaa bbb__ccc__ddd eee__`, `aaa bbb` and `ddd eee` could be interpreted as wildcards, while `ccc` may not be a wildcard but could still be interpreted ambiguously like one. In such cases, the order in which `__` appears becomes extremely sensitive, and it can become difficult to determine what the correct interpretation should be.
