### ISSUE TITLE
Impact Pack won't import

### ISSUE THREAD

**Issue by AIMusicExperiment** [ltdrdata/ComfyUI-Impact-Pack#171] opened 2023-09-18 17:52 UTC
Since this mornings up date Impact won't load. . .Help please

**Comment by AIMusicExperiment** [comment] 2023-09-18 17:58
reverted to last commit and all is well

**Comment by tusharbhutt** [comment] 2023-09-18 18:46
The error I get is:

### Loading: ComfyUI-Impact-Pack (V4.8)
Traceback (most recent call last):
  File "C:\Applications\StableDiffusion\ComfyUI\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 99, in <module>
    from impact.special_samplers import *
ModuleNotFoundError: No module named 'impact.special_samplers'

Cannot import C:\Applications\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.special_samplers'

**Comment by fuzzyfaraway** [comment] 2023-09-18 20:40
Slightly different wording, but same problem.

```
### Loading: ComfyUI-Impact-Pack (V4.8)
Traceback (most recent call last):
  File "D:\~Stable Diffusion\~ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\~Stable Diffusion\~ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 99, in <module>
    from impact.special_samplers import *
ModuleNotFoundError: No module named 'impact.special_samplers'
```

**Comment by lord-lethris** [comment] 2023-09-18 22:01
Possibly duplicate of issue #170

**Comment by ltdrdata** [comment] 2023-09-18 22:29
It is just patched.. My fault...

**Closed as completed by ltdrdata** 2023-09-18 22:29 UTC
